Release for GATE ESP32 Alarm/Modbus/Http 1.1.0-2034C
GrentonSmartHome/GrentonSmartHome.github.io pull request #16
Opened 2020-10-14 11:10 UTC by kjurek-gn

- add RN for devices Alarm/Modbus/Http 1.1.0-2034C
- add update datasheets for Alarm/Modbus/Http devices

2020-10-14 11:29 UTC, gwachocki approved these changes

2020-10-15 10:32 UTC, qhash91 requested changes
Gdyby udało się Piotrowi dorzucić certy to proponuje poprawić jeszcze.

2020-10-15 10:32 UTC, qhash91 commented on en/datasheets.md
> +GATE ALARM INT-221-E-01 | [Datasheet](http://files.grenton.com/docs/datasheets/datasheet_CLU_Gate_Alarm_1.1.3-1942.pdf) | [Manual](http://files.grenton.com/docs/instructions/instruction_Gate_Alarm_1.
Proponowałbym dorzucenie do serwera certyfikatu. Nasze oficjalne dokumenty powinny jednak być podpisane przez nas. Rozmawiałem z Piotrem Błaszczykiem spróbuje to dorzucić.

2020-10-15 10:32 UTC, qhash91 commented on pl/datasheets.md
> +GATE ALARM INT-221-E-01 | [Karta Katalogowa](http://files.grenton.com/docs/datasheets/Dokumentacja_techniczna_Gate_Alarm_1.1.3-1942.pdf) | [Instrukcja](http://files.grenton.com/docs/instructions/inst
To samo co powyżej

2020-10-20 10:04 UTC, qhash91 commented on en/datasheets.md
> +GATE ALARM INT-221-E-01 | [Datasheet](http://files.grenton.com/docs/datasheets/datasheet_CLU_Gate_Alarm_1.1.3-1942.pdf) | [Manual](http://files.grenton.com/docs/instructions/instruction_Gate_Alarm_1.
Do poprawienia w przyszłości

2020-10-20 10:05 UTC, qhash91 commented on pl/datasheets.md
> +GATE ALARM INT-221-E-01 | [Karta Katalogowa](http://files.grenton.com/docs/datasheets/Dokumentacja_techniczna_Gate_Alarm_1.1.3-1942.pdf) | [Instrukcja](http://files.grenton.com/docs/instructions/inst
Do poprawienia w przyszłości

2020-10-20 10:05 UTC, qhash91 approved these changes

2020-10-20 10:05 UTC, merged